### ISSUE TITLE
Outdated Documentation

### ISSUE THREAD

**Issue by Sekuraz** [veos-sxarr-NEC/veos#2]
https://github.com/veos-sxarr-NEC/veos/blob/ed2b69e8381cc1c137cf9a7545e25b6c6cc3facf/src/veos/amm/pmap.c#L65
Here pgsize is not even a parameter to the function, so mentioning it in the Documentation does not make any sense. Please update it :)

**Comment by veos-sxarr** [comment]
Hello,

Thank you for pointing out. We will fix the line.

**Comment by veos-sxarr** [comment]
We have updated the documentation of isheap() function.
https://github.com/veos-sxarr-NEC/veos/blame/master/src/veos/amm/pmap.c

Let us close this issue.
